### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hynsey777** [Project-Mega-Pack/amp-aircraft-a330-300#100]
**Description**
Screen next to pfd which shows flight play doesn't work
**Steps to reproduce**
When turning on external power or batteries  and then cant get it to go away
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/80136463/110190184-f2ef8e00-7e19-11eb-948c-3ea818f8a5fe.png)

**Additional context**

**Comment by Clink1234** [comment]
Not compatible with a32nx or abadstudios planes.
