### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tjugpal** [Project-Mega-Pack/amp-aircraft-a330-300#101]
Not a bug, but, the engines neeed to be shaped a little different. Currently they look like A340 engines and not the A330 engines. Good work on the project!

**Comment by tjugpal** [comment]
![404px-Trent_700_-_DSC_8123-F-WWCR_-_MSN_1462_(10513329855)_(cropped)](https://user-images.githubusercontent.com/68529153/110195927-cc1f6080-7df5-11eb-82c4-04af97279f77.jpg)

The 330 engines are a bit more flat

![CFM56_engine_of_an_Airbus_A340](https://user-images.githubusercontent.com/68529153/110195932-d7728c00-7df5-11eb-8f6e-45f36a04b6f0.jpg)

The 340 ones are more rounded.

**Comment by Clink1234** [comment]
Looks the same to me. Duplicate to #14

**Comment by tjugpal** [comment]
Look at the bottom curvature in reference to where the reverse doors are. The 340 starts curving slightly before the front end of the doors and the 330 starts midway through. I'll try and get better pictures.
