### ISSUE TITLE
[Model] Model Accuracy Issues

### ISSUE THREAD

**Issue by RealPerseus** [Project-Mega-Pack/amp-aircraft-a330-300#102]
**Description**
You are likely already aware of many of these issues. Several smaller issues not listed here have been mentioned by others. You can probably find more inaccuracies yet to be mentioned too.
Love to help out to make this realistic!

**Steps to reproduce**
1. Load the aircraft in any location or livery.
2. Observe.

**Expected behavior**

**Screenshots**
SimAPU:
![image](https://user-images.githubusercontent.com/80144319/110197241-81a6df80-7e07-11eb-9c1d-04cf4fcab5c0.png)
Notice the flat tailcone top and oblong apu exhaust duct. The strobe shroud is also oversized. The shapes seem very blocky.

RealAPU:
![image](https://user-images.githubusercontent.com/80144319/110197181-0c3b0f00-7e07-11eb-98d6-c0020a191bff.png)
![image](https://user-images.githubusercontent.com/80144319/110197202-3d1b4400-7e07-11eb-9913-416dc5c118e4.png)
The tailcone gently slopes down, the apu exhaust duct is circular, and the strobe shroud is much smaller.

Sim cabin windows:
![image](https://user-images.githubusercontent.com/80144319/110197340-3d680f00-7e08-11eb-9b3d-7d668fb12396.png)
Airbus widebodies have a characteristic curve of the cabin windows near the rear tail area. The A330 windows in-sim are completely straight. The windows also appear to be too large (might just be me)

Real cabin windows:
![image](https://user-images.githubusercontent.com/80144319/110197334-317c4d00-7e08-11eb-80fe-45833897841d.png)
You can see from the line the windows gently angle upwards on the real A330.

Sim anti-shock bodies.
![image](https://user-images.githubusercontent.com/80144319/110197407-b5ced000-7e08-11eb-984e-0e21da441333.png)
Self explanatory. They are floating.

Sim trent 700 exhaust
![image](https://user-images.githubusercontent.com/80144319/110197479-00e8e300-7e09-11eb-90f4-fd5d67ccf9fe.png)
The core of the engine is very oversized. There is very little open space for the bypass duct.

Real trent 700 exhaust
![image](https://user-images.githubusercontent.com/80144319/110197539-69d05b00-7e09-11eb-858e-cf1bcac81c5e.png)
from this image, you can see that you should be able to clearly see the fan blades from the rear. 

Some other misulanious issues:
![image](https://user-images.githubusercontent.com/80144319/110197649-51147500-7e0a-11eb-87ed-29a285b8cef5.png)
Cockpit windows have an incorrect shape.

![image](https://user-images.githubusercontent.com/80144319/110197717-af415800-7e0a-11eb-9baf-f006a573f6b1.png)
You can see the middle windows gently slope rather than jut upwards. This is the most noticeable issue. (Ignore the drawn lines)

**Additional context**

**Comment by Amen-05** [comment]
yeah many other people have noticed the cockpit windows being out of shape. It would be nice to see them being a bit smaller and in the correct shape.

**Comment by Clink1234** [comment]
Duplicate to #14
