### ISSUE TITLE
[BUG] PFD Display Speed

### ISSUE THREAD

**Issue by FSRicy** [Project-Mega-Pack/amp-aircraft-a330-300#103]
I dont know how to recreate the bug but, during takeoff
 the speed display in the PFD went erratic and displayed speeds between 0-80 knots, then it reverted back to it`s actual speed where it was overspeeding.

Surprisingly, no stall warning was sounded off

Weather had no chance of icing and it happened at low altitude during climb.

![20210306170428_1](https://user-images.githubusercontent.com/80148752/110200150-d138ea00-7e9f-11eb-892e-2dfaf6300234.jpg)

**Comment by Clink1234** [comment]
Pitot heat. Same thing happens on all airbus planes in the game.
