### ISSUE TITLE
[BUG] Screens Problem

### ISSUE THREAD

**Issue by Jus-de-Pom** [Project-Mega-Pack/amp-aircraft-a330-300#105]
**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Jus-de-Pom** [comment]
Hello,
I don't know if I did something wrong but the screens on the A330 don't work even if I start directly in the air or on the runway.
Here is a screenshot :
![20210306143406_1](https://user-images.githubusercontent.com/80160607/110208731-33d2bb80-7e89-11eb-9a65-c5597bc524ff.jpg)

**Comment by Starseed55** [comment]
I can confirm the same issue No FMC, MFD,PFD and N1 not showing ??

**Comment by Clink1234** [comment]
Not compatible with a32nx or abadstudios planes.
