### ISSUE TITLE
[BUG] Installed a few times a330-300 v2, but instrument never light-up, allways off?   

### ISSUE THREAD

**Issue by suprafax** [Project-Mega-Pack/amp-aircraft-a330-300#108]
**Before Creating, Please Make sure this is not a duplicate issue. Further, our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.**

**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Clink1234** [comment]
our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.
