### ISSUE TITLE
[BUG] Brake Action/Landing Speed

### ISSUE THREAD

**Issue by Asianblade** [Project-Mega-Pack/amp-aircraft-a330-300#109]
**Description**
This A330 aircraft performs like the A320, but the cockpit/textures are relocated. This causes the aircraft to be not really realistic, when the plane lands, it looks like the plane is going really slow, and the brakes stop the plane too quickly.

**Steps to reproduce**
Steps to reproduce the behaviour:
1.  This should all be connected to the speed since it doesn't perform like an A330.
2. When I put my autobrakes to 'Low', it's like I'm stopping at Medium autobrake (Compared to the real thing)

**Expected behaviour**
The speed of the aircraft on the ground should be at a faster pace, that way it will be way more realistic while on the ground.

**Comment by Clink1234** [comment]
The plane does not perform like an a320. However, flight model improvements will be coming soon.
