### ISSUE TITLE
[BUG]its dusn't work at all. All the buttens say 'foult' and can't be pressd, and it won't start, even with ctrl+e or if you start on the runway. This is allways, even if i reset the fligt, the flightsimulator or my computer. i even reinstalled the addon. I never got it working.

### ISSUE THREAD

**Issue by MkDtheGAMER** [Project-Mega-Pack/amp-aircraft-a330-300#114]
**Before Creating, Please Make sure this is not a duplicate issue. Further, our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.**

**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Clink1234** [comment]
our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.
