### ISSUE TITLE
screens

### ISSUE THREAD

**Issue by keanie69** [Project-Mega-Pack/amp-aircraft-a330-300#117]
**Before Creating, Please Make sure this is not a duplicate issue. Further, our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.**

**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Clink1234** [comment]
NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.
