### ISSUE TITLE
[BUG] Screens not showing up. BAT 0 on Battery Switches/ 

### ISSUE THREAD

**Issue by sahajshah21** [Project-Mega-Pack/amp-aircraft-a330-300#119]
**Before Creating, Please Make sure this is not a duplicate issue. Further, our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.**

**Description**
I turned on both the battery and external power switches and they didn't turn. I then realized the battery was at 0.0 opposed to 28.0. I have the compatibility mod and everything so it should be working. What can I do?

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by okurz** [comment]
Make sure to use A32NX in the development version from master branch, not the release version and not the "cfbw" version

**Comment by Clink1234** [comment]
our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.
