### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JacobB213** [Project-Mega-Pack/amp-aircraft-a330-300#120]
**Before Creating, Please Make sure this is not a duplicate issue. Further, our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.**

**Description**
When using autopilot it goes full ruder left and start to shake and its noticeable in the cockpit, window seat and exterior view but only happens when using autopilot and not hand flying

**Steps to reproduce**

**Expected behavior**
i expected the plane to behave normally and not look like its about to shake its self to pieces

**Screenshots**
no and if i do it would be a clip and thats buried under a load of different ones
**Additional context**
it happends even when i fully restart MFS2020 and restart the flight also it doesnt happen when the AI pilot flys on autopilot

**Comment by Clink1234** [comment]
#9
