### ISSUE TITLE
[BUG] with the weather 

### ISSUE THREAD

**Issue by Dabschi** [Project-Mega-Pack/amp-aircraft-a330-300#123]
**_if you fly the A330 through rain, it will later no longer be able to maintain its altitude and speed correctly_**

I haven't found a way to fix it yet, but it ONLY happens when you're flying through rain

**Comment by Dabschi** [comment]
and i think maybe the 330 has a problem with the live weather

**Comment by Clink1234** [comment]
Nope. turn on pitot heat.
