### ISSUE TITLE
[BUG] DESCENT speed incorrect

### ISSUE THREAD

**Issue by EFSCH** [Project-Mega-Pack/amp-aircraft-a330-300#124]
DESCENT speed too high (448 kts)
using latest MSFS2020 Level1.14.5.0 and A330 V0.2 

When entering OP DES phase, the speed jumps to 448 kts. The related PERF DES page is defining 173 kts in my example.  
When I define the same 'supposed to be managed speed' as selected speed, it works.

[A330 OP DES Problem.pdf](https://github.com/Project-Mega-Pack/amp-aircraft-a330-300/files/6116038/A330.OP.DES.Problem.pdf)

**Comment by TheCubeHamster** [comment]
+1 to this - FD sets target speed to 448 without fail on descent. Usually starts when passing through FL200 or so.

**Comment by Clink1234** [comment]
#22 duplicate
