### ISSUE TITLE
[BUG] Landing Gear Does Not Come Up

### ISSUE THREAD

**Issue by CaptainRyan17** [Project-Mega-Pack/amp-aircraft-a330-300#128]
**Description**
 An issue that has happened to me was after I rotated off the runway, tried to pull the gear up but it just didn't come up. 

**Steps to reproduce**
1. Take off
2. Gear Up
3. Gear is not coming up 

**Expected behavior**
The gear to come up when I hit G or when I do it manually.

**Screenshots**
![Microsoft Flight Simulator Screenshot 2021 03 10 - 23 30 43 20_LI (2)](https://user-images.githubusercontent.com/80078912/110736587-ed1ef180-81f9-11eb-9151-a386a1ccdefa.jpg)
![Microsoft Flight Simulator Screenshot 2021 03 10 - 23 29 56 04_LI](https://user-images.githubusercontent.com/80078912/110736589-edb78800-81f9-11eb-9319-12ba38c6778c.jpg)

**Comment by Clink1234** [comment]
never had this reported before. reload the game and try again, could just be a one time thing.
