### ISSUE TITLE
Unrealistic A330 Landing Gear issue. (explained in the paragraph)

### ISSUE THREAD

**Issue by kanmomo001** [Project-Mega-Pack/amp-aircraft-a330-300#130]
the landing gear for the A330 just goes into the down position when i land. Even when i absolutely butter the landing, it just goes down like in FSX. The landing gear does not have any resistance like in the real life A330. No animation between when initial contact with the ground and full contact. Can you fix that for the A330 so that the landing gears have more resistance when touching down. What i mean is that in the plane spotting videos, the planes at least ride for a few seconds on the back wheel of the wing gears before fully coming down.  Its a major issue that I have with it. The landing gear has only 2 postions, up and down for the ingame one. So can you make the landing gear so that when landing, there is more bounce and resistance with contact for landing. That would be really appreciated as landings will be more realistic

**Comment by Amen-05** [comment]
that's true, but sadly, in mfs2020, (according to a dev from the PMP team), the game does not recognize the a330's gear tilt on the ground, causing this to happen. therefore it's impossible to roll on the runway on the rear gear on touchdown

**Comment by Clink1234** [comment]
sadly, no. this is a msfs limitation. we will continue to improve where able.
