### ISSUE TITLE
Speed brake stays in the middle and you can not move[BUG]

### ISSUE THREAD

**Issue by cromsan** [Project-Mega-Pack/amp-aircraft-a330-300#131]
**Before Creating, Please Make sure this is not a duplicate issue. Further, our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.**

**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cromsan** [comment]
speed brake stays at the middle and you can not move the lever with the mouse or assign a key of the throttle hotas warthog

**Comment by Clink1234** [comment]
duplicate to #4 . use a keybind or peripheral for now.
