### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Triple3G** [Project-Mega-Pack/amp-aircraft-a330-300#133]
**Before Creating, Please Make sure this is not a duplicate issue. Further, our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.**

**Description**
A330-300 does not use its reserve fuel tanks when their main fuel tanks get low.

**Steps to reproduce**
1. Load in the A330-300 with fuel
2. Fly the plane until inner fuel tanks are at low percentages 
3. Realize that you are 37,000 feet in the sky when the reserve tanks aren't working
4. Manually switch over fuel with the slider in MFS2020

**Expected behavior**
For the fuel to automatically pump into the main fuel tanks.

**Screenshots**

**Additional context**

**Comment by Clink1234** [comment]
Known asobo issue. you need to manually switch over rn.
