### ISSUE TITLE
Fly By Wire Compatibility

### ISSUE THREAD

**Issue by Carman1000** [Project-Mega-Pack/amp-aircraft-a330-300#134]
I Love to use this A330, but also Like to use the Fly By Wire A32NX.
But here is the problem;
Both the A330 and the Fly By Wire Reference (and in FBW's case modify) the default A320, meaning if I want to use the A330 I have to uninstall the FBW or the A330 wont work because it is trying to reference modified files.

I would like to ask if the Developers of the A330 could make it such that the A330 does not have to reference the default A320 and instead make it completely independent of the default A320 so that this issue does not occur.

I imagine this is not exactly possible on the other end because otherwise the MegaPack liveries would not work (initially) with the FBW and they would all have to be rewritten to be used by a separate aircraft. (don't quote me on that as I only have a basic understanding of how it all works, and not nearly enough to fix the issue myself)

**Comment by Carman1000** [comment]
Actually, if anyone knows how to get in touch with the guys doing the A321, tell them the same thing...

**Comment by Clink1234** [comment]
in progress.
