### ISSUE TITLE
ND and Autopilot issues

### ISSUE THREAD

**Issue by Ducksneedhelp** [Project-Mega-Pack/amp-aircraft-a330-300#135]
My ND is not showing up anywhere. As well the autopilot is just randomly turning left and right and not following the flight plan. when I switch on the autopilot. There's never been a time where the autopilot has successfully gone right as well. I even deleted the A32NX mod but it still doesn't work.

![autopilot break](https://user-images.githubusercontent.com/69145254/111742318-4507c900-8888-11eb-886e-fb21eac2a080.PNG)

**Comment by Clink1234** [comment]
something on your end. clear out community and reinstall fresh and try again.
