### ISSUE TITLE
Issues, A330-300, 01.03.2021

### ISSUE THREAD

**Issue by kristian1987** [Project-Mega-Pack/amp-aircraft-a330-300#15]
VR: Very blurry looking out of cockpit windows. 
Zoom with right-click does not work both in flat-screen and VR.

Climb detent is very difficult to hit with a Honeycomb Bravo. 
Distance reader to destination in flightplan is frozen.

**Comment by Clink1234** [comment]
Blurry windows are fixed in latest update, throttle issue is known, please provide a more detailed explanation in separate issues for the other issues.
