### ISSUE TITLE
[BUG] MSFS V 1.18.14.0 - External Instrument View for A321 & A330 Mods   

### ISSUE THREAD

**Issue by EFSCH** [Project-Mega-Pack/amp-aircraft-a330-300#162]
**Before Creating, Please Make sure this is not a duplicate issue. Further, our aircraft is NOT COMPATIBLE with abadstudios or A32nx, YOU MUST UNINSTALL THEM BEFORE USE.** - done !

**Description**

Since Level 1.18.14.0 ,the external view of both planes show wrong instruments, see attachment. In a forum someone mentioned the same problem was there with the fly-by-wire Mod. The fix must go into the cockpit.cfg file. Pls fix this !

**Steps to reproduce**

any flight definition using available A321 & A330 downloads.

**Expected behavior**

You can actually fly the aircrafts .. 

[A321 & A330 Problem.pptx](https://github.com/Project-Mega-Pack/amp-aircraft-a330-300/files/6940880/A321.A330.Problem.pptx)

**Comment by EFSCH** [comment]
Latest A330-300 Version 0.2.2 does not solved the problem.

**Comment by adenaud** [comment]
If you really miss it you can edit the cockpit.cfg file in PMP_A330_300\SimObjects\Airplanes\amp-airbus-a330-300
 
At the end of the file add `vcockpit_hud = 1` underthe MISC section:
```
[MISC]
g_meter=0
vcockpit_hud = 1
```

**Comment by EFSCH** [comment]
Thx for the fix.
