### ISSUE TITLE
[BUG] spoilers stick and constraints not followed

### ISSUE THREAD

**Issue by darkfury334** [Project-Mega-Pack/amp-aircraft-a330-300#17]
**Description**
Spoilers lever will not retract past 50% and constraints not followed on approach

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Fly A330 on approach (ILS) in managed mode
2. Click on manage mode on AP for approach (before first constrain)t. Use mouse on spoiler lever to control amount of spoilers (50% or more)
3. wait till next constraint and try retracting spoilers using lever
4. altitude does not change and spoilers lever sticks between 50% and 100%

**Expected behavior**
Spoilers to be able to be fully retracted and altitude constraints followed.

**Screenshots**

**Additional context**

**Comment by Clink1234** [comment]
This is a known issue and is already documented. For now use a keybind or peripheral for the spoilers.
