### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by captainemirates** [Project-Mega-Pack/amp-aircraft-a330-300#19]
**Description**
The panels nor the MCDU are working no matter what I try.

every time I load up the aircraft no matter what livery I am using and no matter how much times I start it the panels nor the MDCU work.
![image](https://user-images.githubusercontent.com/79878948/109570059-74ac8800-7ab7-11eb-8c34-904964e3657b.png)

**Comment by Clink1234** [comment]
You can not use A32nx while using this mod. They are not compatible.
