### ISSUE TITLE
[BUG] Auto Thrtottle disabling it self when Throttle is put on Idle.

### ISSUE THREAD

**Issue by VitorMD11** [Project-Mega-Pack/amp-aircraft-a330-300#27]
**Description**
The Auto Thrust disables it self if the Throttle is manually set to Idle.

**Steps to reproduce**
1. Manually put your throttle at any level that is not idle.
2. Enable the Auto Thrust.
3. Manually put your throttle to idle.
4. The Auto Thrust is going to disable itself.

**Expected behavior**
What was expected to happen is to have the Auto Thrust still enabled even if the Throttle is manually set to Idle.

**Additional context**
This can happen in any stage of the flight.
![image](https://user-images.githubusercontent.com/79885080/109585792-e6e69200-7ae2-11eb-9da5-1a8e2ce17cd0.png)

![image](https://user-images.githubusercontent.com/79885080/109586507-19dd5580-7ae4-11eb-86c2-0da2450dc01e.png)

**Comment by Clink1234** [comment]
This is not a bug, and is accurate to the real life operation of the aircraft. If you idle the throttles, the autothrottle disengages.

**Comment by VitorMD11** [comment]
> This is not a bug, and is accurate to the real life operation of the aircraft. If you idle the throttles, the autothrottle disengages.

Oh ok, i didn't know that, thanks and sorry for putting up a useless report hahahah hope i didn't messed with anything.
