### ISSUE TITLE
[BUG] Multiplayer only shows cockpit

### ISSUE THREAD

**Issue by rayos006** [Project-Mega-Pack/amp-aircraft-a330-300#31]
**Description**
Playing multiplayer with people who have the A330 installed only renders the cockpit in game.

**Steps to reproduce**
1. Load into the game with another player who has the A330.
2. See flying cockpit.

**Expected behavior**
Render of plane appear instead of flying cockpit.

**Screenshots**
![missing_plane](https://user-images.githubusercontent.com/20158338/109600117-c8c86400-7ad9-11eb-93e2-65cc9c6fae95.PNG)

**Comment by Hamiltonoshane** [comment]
you has 32XN in the community?

**Comment by rayos006** [comment]
Nope, We did not have Fly By Wire in the community folder.

**Comment by Clink1234** [comment]
Fixed. In next version.
