### ISSUE TITLE
[BUG] Speed Brake stuck at 50 percent

### ISSUE THREAD

**Issue by ryanhallyyc** [Project-Mega-Pack/amp-aircraft-a330-300#32]
**Description**
speed brake does not shift back to 0% after setting it to 50%

**Steps to reproduce**
mouse control the speed brake to 50 percent, then try to reduce to 0 percent

**Expected behavior**
control lever does not move back to 0 percent

**Comment by Clink1234** [comment]
Duplicate to #4 . For now use a peripheral or keybind.
