### ISSUE TITLE
Losing speed

### ISSUE THREAD

**Issue by swausb** [Project-Mega-Pack/amp-aircraft-a330-300#35]
Hey,
one example:

you are on 30k ft with your plane, set the speedbrake full and want to descend to 22k ft, the autopilot puts the plane on 60(max) vertical speed and starts losing speed. I think it should increase its speed while descending with 60 vertical speed?

Kind regards

**Comment by Clink1234** [comment]
You should not descend with speedbrakes out. Speed issues are duplicate to #16
