### ISSUE TITLE
VR and Fuel

### ISSUE THREAD

**Issue by Marco138** [Project-Mega-Pack/amp-aircraft-a330-300#37]
1) i make now a test flight from eddf to wsss aircraft feels and flys well. But there is one major think... i fly in Virtual Reality and the mouse can use only when i close one eye to navigate. there is a double effect. 

2) with a full Tank i can Fly from Frankfurt to Sydney?

i on Fly EDDF to WSSS and i have planed 76tonnes of fuel....
Arr in Singapur i have rest of 35Tonnes...

There must be something wrong...

3) After Takeoff when i direkt use AP aircraft runs do full power and doesnt manage clb speed.. after 1 min aircraft break and it runs normal...

4) with thrustmaster TCA thrustclimb not perfect managed to basesettings of the throttle

BEST REGARDS 
and big thanks for your work for us all

**Comment by Clink1234** [comment]
Duplicate to #33
