### ISSUE TITLE
[BUG] Reverse Thrust levers dont animate

### ISSUE THREAD

**Issue by bravadoh** [Project-Mega-Pack/amp-aircraft-a330-300#40]
**Description**
When selecting reverse thrust the reverser levers do not move upwards with the levers when moving into the reverse detent

**Steps to reproduce**
1. Go to Thrust levers
2. move from idle into reverse
3. Levers move down but reverse levers do not move

**Expected behavior**
The reverser levers should come up

**Screenshots**
Video showing issue
https://youtu.be/IFKzfa-_t6Y?t=321

**Additional context**
Using full TCA quadrant with add-ons

**Comment by Clink1234** [comment]
Duplicate to #7
