### ISSUE TITLE
Speed brake lever issue

### ISSUE THREAD

**Issue by StormBoi98** [Project-Mega-Pack/amp-aircraft-a330-300#41]
**Description**
basically whenever i use the speed brakes i can never get them to retract down fully because of an issue with the speed brake lever.

**Steps to reproduce**
once in the cockpit raise the speed brakes and try to lower them again and it will only go back half way

**Expected behavior**
it is expected to go back into position completely 

**Screenshots**
here is a link to a youtube video demonstrating the issue  https://www.youtube.com/watch?v=tZw6J9_LAOg

**Comment by Clink1234** [comment]
Duplicate to #4 for now use keybinds or peripherals
