### ISSUE TITLE
[BUG] A330 300 fuel usage not precise

### ISSUE THREAD

**Issue by Serratus61** [Project-Mega-Pack/amp-aircraft-a330-300#44]
**Description**
I used the a330 300 for a flight from **Madeira Airport LPMA** to **Tokyo Haneda RJTT** 100% fully tanked **with increased sim rate** and as soon i reached tokyo, there was 70 % left in the fuselage. i dont know if it is because of the sim rate or not...

**Steps to reproduce**
1. Increase Sim Rate
2. Full Tank
3. Fly long distances
4. See decreased fuel usage error

**Expected behavior**
The A330 300 should have run out of fuel or should have more fuel burned

**Comment by Clink1234** [comment]
Try it without increased sim rate, and if it works, there's no issue. We do not support increased sim rates. If the issue persists, reopen a new bug report.
