### ISSUE TITLE
Texture Bug on the Wing 

### ISSUE THREAD

**Issue by Lasagneboy11** [Project-Mega-Pack/amp-aircraft-a330-300#46]
Hello dear Developer i wanted do ask if you can Fix the texture bug on the Wing by the Flaps pls here is a picture what i mean 
![2B637985-D2FB-4531-B70D-79A9CFED8716](https://user-images.githubusercontent.com/79940853/109717092-ebc04a00-7ba5-11eb-9194-54b6c2ca92d4.jpeg)

**Comment by Clink1234** [comment]
After investigation it was shown that this is an issue with your livery. It is not an issue with our plane or any liveries in our mega pack.
