### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by teddyknowsbest** [Project-Mega-Pack/amp-aircraft-a330-300#47]
**Description**
Animation freezes mid-flight. I'm able to look around bu the aircraft isn't moving and the GPS is frozen. The buttons are inoperable. 

**Steps to reproduce**
Unsure. Leave it on  Autopilot for a bit

**Expected behavior**
They keys in the cockpit become inoperable. I can rotate the view and switch between cameras, but the aircraft isn't moving. 

**Screenshots**
Don't have them

**Additional context**
I love this job on this aircraft, so I just wanna see it get better

**Comment by Clink1234** [comment]
Seems like your sim just froze. If it happens again record a video/screenshots.
