### ISSUE TITLE
Auto throttle doesn't work when you change your speeds and it won't go to new speed it will stay at old speed and whenever you change speed on autopilot you need to engage and disengage auto throttle each time.

### ISSUE THREAD

**Issue by Scoocie** [Project-Mega-Pack/amp-aircraft-a330-300#52]
#**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Clink1234** [comment]
Not for me. Make sure you press in the speed select button. This is a desired and accurate feature.
