### ISSUE TITLE
[BUG] A330 Crashes my game upon starting a flight.

### ISSUE THREAD

**Issue by MassiveShitAndFart** [Project-Mega-Pack/amp-aircraft-a330-300#58]
For an unknown reason, my A330 has crashed my game upon starting every flight I try with it. I had to uninstall it and the liveries and only then could I fly. I have no idea what caused the crashes as I installed the latest version (0.2) of the aircraft. My MSFS is updated too. I reinstalled the A32NX and am still waiting to see if the cockpit is glitched out as that issue occurred after uninstalling the A330 and replacing the A32NX into my Community folder. I am aware that the A330 does not function correctly with the A32NX installed but I made sure to remove the A32NX from my Community folder before installing the A330.

**Comment by Clink1234** [comment]
Crash issues are usually client side. clear out community and try again.
