### ISSUE TITLE
[BUG] Weird Things Happening To The Airspeed Indicator

### ISSUE THREAD

**Issue by InsertRandomPlaneHere** [Project-Mega-Pack/amp-aircraft-a330-300#59]
**Description**
Weird Buggy Airspeed Indicator.

**Steps to reproduce**
Steps to reproduce the behaviour 
Im unsure on how to repeat i was messing about in papua near where afp95 did a video and the airspeed indicator suddenly became bugged a few mins after i put autopilot on.

**Screenshots**
![Screenshot 2021-03-03 114548](https://user-images.githubusercontent.com/79932674/109801416-57da9680-7c16-11eb-96be-35969cd6f16b.png)
![Screenshot 2021-03-03 114631](https://user-images.githubusercontent.com/79932674/109801431-5d37e100-7c16-11eb-8fc6-5b945ff3fb2f.png)

**Comment by InsertRandomPlaneHere** [comment]
okay it seems to have fixed itself a bit afterwards still weird tho
was ongoing for 5 minutes

**Comment by Clink1234** [comment]
Your pitot tubes iced over. this happens in the a320 as well. turn on pitot heat.
