### ISSUE TITLE
MISSING APPROACHES IN FMC[BUG]

### ISSUE THREAD

**Issue by olivers1989** [Project-Mega-Pack/amp-aircraft-a330-300#70]
Hello, im missing the whole approaches at FSIA.
Im using Navigraph Navdata in newest Version but i have only one for selection ... 
![approach](https://user-images.githubusercontent.com/79992569/109839679-a5232c00-7c47-11eb-94f0-21a49926b3ae.PNG)

**Comment by Clink1234** [comment]
Seems like a base-game issue. I suggest setting up flights in the in game menu and not in the MCDU.
