### ISSUE TITLE
On the 330 new release version 0.2.0 the displays are not displaying, I have the same issue with the a321[BUG]

### ISSUE THREAD

**Issue by xbbjhce** [Project-Mega-Pack/amp-aircraft-a330-300#71]
**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xbbjhce** [comment]
On the 330 new release version 0.2.0 the displays are not displaying, I have the same issue with the a321

**Comment by Clink1234** [comment]
Dont use A32nx or abad planes with this mod
