### ISSUE TITLE
Sound in the cockpit is the same as the sound in the exterior.

### ISSUE THREAD

**Issue by Amen-05** [Project-Mega-Pack/amp-aircraft-a330-300#74]
**Description**
This issue has been talked about on the discord: the sound heard in the cockpit is the same as the sound heard near the engine. It is as loud and as annoying. The engine roar can be heard throughout the entire flight from the flight deck

**Steps to reproduce**
1. a330-300
2. set TO/GA
3. listen to the sound from the wing view and then listen to it from the flight deck

**Expected behavior**
The noise should be severely reduced and the engine roar should only be heard in TO/GA mode and therefore removed during cruise.

**Comment by Clink1234** [comment]
It isn't for me... if you think theyre loud you can lower engine noise in the settings.
