### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by louisjknowles** [Project-Mega-Pack/amp-aircraft-a330-300#82]
**Description**
I noticed on final that the aircraft nose was struggling to be dipped forwards without applying a lot of thrust, even at a steady speed around 150kts, the plane was becoming rather inoperative  (vertical wise). It seemed like the plane would eventually go into a stall if full thrust isnt applied every now and then

**Expected behavior**
A usual approach

**Screenshots**

**Additional context**

**Comment by Clink1234** [comment]
This is just the way the plane flies. duplicate to all of our flight model improvement issues.
