### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CCZO6** [Project-Mega-Pack/amp-aircraft-a330-300#84]
**Description**
When using the full range of motion of pitch and roll controls, the sidestick only appears to move up and to the left, and down and to the right.

**Steps to reproduce**
1. Enter cockpit
2. Move pitch control up and down
3. Move roll control left and right

**Expected behavior**
Expected sidestick to have full range of motion

**Screenshots**

**Additional context**

**Comment by Clink1234** [comment]
duplicate to #73
