### ISSUE TITLE
[BUG] Player controlled A330 in multiplayer partially in the ground

### ISSUE THREAD

**Issue by Winter-huntsman** [Project-Mega-Pack/amp-aircraft-a330-300#86]
**Description**
In multiplayer, any other users using the A330-300 will appear lower to the ground to the point of clipping through it. This has been seen on all players on the ground in the A330 for me. This also happen for all AI.

**Steps to reproduce**
1. Go to any airport and look for a user in the A330
2. Go to look at the players plane and observe the ground clipping

**Expected behavior**
According to what I have been told they should be on the ground normally with wheels on pavement. This is a known Issue for AI but for player controlled planes, this should not be happening.

**Screenshots**
First is of a player (Plane top left of screen) parked at gate and plane is partially in ground. Second pic at a different airport had similar thing but not as deep into the ground (and yes this person did have a AI A380 on top of him)
![1250410_screenshots_20210303132926_1](https://user-images.githubusercontent.com/79963878/110019176-c179a400-7ced-11eb-9c45-6a3308f27c10.jpg)
![1250410_screenshots_20210304113348_1](https://user-images.githubusercontent.com/79963878/110019186-c3dbfe00-7ced-11eb-9bab-245c310679ea.jpg)

**Additional context**
While I have seen a lot of A330s in the air or while I was flying I have only ever seen 3 actually on the ground, and only started getting photos of the last 2. Will continue to document the problem and upload more photos as this error is seen.

**Comment by Clink1234** [comment]
This is a well known asobo thing. You'll also see planes with no gear. Is what it is sadly. Either way, there's nothing we can really do about it
