### ISSUE TITLE
during flight, The new A330 and The A321, The rudder looks stuck to the left

### ISSUE THREAD

**Issue by elderba** [Project-Mega-Pack/amp-aircraft-a330-300#90]
![DDF81D25-EC4D-4F75-A467-2F86AC0843F9](https://user-images.githubusercontent.com/80073927/110041364-48f20200-7d44-11eb-96b4-828117ce372a.jpeg)
![9D69FC2A-593C-44CC-BD0B-36C90F6FF5C6](https://user-images.githubusercontent.com/80073927/110041380-4c858900-7d44-11eb-966f-497b3c5e5c7d.jpeg)

**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by elderba** [comment]
I have removed The MX32 do community and still doesnt work_

**Comment by Clink1234** [comment]
Duplicate to #88
