### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CaptainRyan17** [Project-Mega-Pack/amp-aircraft-a330-300#91]
**Description**
The A330 Autothrottle Keeps giving over speeds, also it cuts in and out, also the power with the auto throttle is either all or none. 

**Steps to reproduce**
1. Fly with autothrottle on climb setting while climbing or flying normally 

**Expected behavior**
Autothrrotle should maintain a clear speed and should know how to adjust the speed

**Comment by Clink1234** [comment]
duplicate to #22
