### ISSUE TITLE
[BUG] Electrical systems shuts off on approach

### ISSUE THREAD

**Issue by hoseth0711** [Project-Mega-Pack/amp-aircraft-a330-300#94]
Hello 
I got an issue where the electrical systems shuts down just before or at approach. 
I remove a32nx mod from community folder but still this happens.
Can you help me please?

**Comment by hoseth0711** [comment]
I’m using the SAS livery from the liveries mega pack and other airplane mods in my community folder is salty 747 and working title Cj4

**Comment by Clink1234** [comment]
This is not an issue from others. Please provide screenshots and/or video of the issue. Could be you ran out of fuel.
