### ISSUE TITLE
my instruments doesnt work. i have uninstall the mod and again installed but it doesnt work[BUG]

### ISSUE THREAD

**Issue by beifi** [Project-Mega-Pack/amp-aircraft-a330-300#96]
**Description**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beifi** [comment]
my instruments doesnt work

**Comment by Clink1234** [comment]
Not compatible with a32nx

**Comment by beifi** [comment]
> Nicht kompatibel mit a32nx

Ah vielen dank für ihre Antwort
