### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CAC14** [Project-Mega-Pack/amp-aircraft-a330-300#97]
**Description**
Throttle problems, air brake problems (which i think you know about) and flap problems.  Also blurry in 4k
see video
https://youtu.be/NVqCA_wnBg8

**Expected behavior**
flap indicator goes away at full flap.  it shouldn't.  Air brakes cant be turned off, they should.  Throttle points arnt right.  they should be.

**Screenshots**
https://youtu.be/NVqCA_wnBg8

**Additional context**

**Comment by Clink1234** [comment]
duplicate to #4
