### ISSUE TITLE
[BUG] Displays not working

### ISSUE THREAD

**Issue by chris1971nrw** [Project-Mega-Pack/amp-aircraft-a330-300#98]
Batterie ON
Ground Power ON

Display black , not working

V.0.2.0
![Microsoft Flight Simulator Screenshot 2021 03 05 - 22 00 23 00](https://user-images.githubusercontent.com/59622205/110173200-8ca94200-7dfe-11eb-9dd0-6f76d50157c3.png)

**Comment by Jus-de-Pom** [comment]
I have the same problem

**Comment by Starseed55** [comment]
I can confirm the same issue as well.......

**Comment by Clink1234** [comment]
Not compatible with a32nx or abadstudios planes
